steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/session-reaper/Dockerfile
      - -t
      - us-central1-docker.pkg.dev/acoustic-result-491711-t7/udd-images/session-reaper:latest
      - .
images:
  - us-central1-docker.pkg.dev/acoustic-result-491711-t7/udd-images/session-reaper:latest
