import type { StackDefinition } from './types.js';

/**
 * Built-in stack definitions ordered by detection priority.
 * More specific stacks (nextjs, react) come before their generic
 * parents (node, static-site) so detectStack resolves correctly.
 */
export const builtinStacks: readonly StackDefinition[] = [
  // ── Specific stacks first ──────────────────────────────────
  {
    id: 'nextjs',
    name: 'Next.js',
    runtime: 'node',
    extensions: ['.ts', '.tsx', '.js', '.jsx'],
    entryPatterns: ['next.config.js', 'next.config.ts', 'next.config.mjs'],
    buildCommand: 'npm run build',
    startCommand: 'npm start',
    testCommand: 'npm test',
    dockerImage: 'node:20-alpine',
    category: 'fullstack',
  },
  {
    id: 'react',
    name: 'React',
    runtime: 'node',
    extensions: ['.tsx', '.jsx', '.ts', '.js'],
    entryPatterns: ['src/App.tsx', 'src/App.jsx', 'src/App.js', 'vite.config.ts', 'vite.config.js'],
    buildCommand: 'npm run build',
    startCommand: 'npm run dev',
    testCommand: 'npm test',
    dockerImage: 'node:20-alpine',
    category: 'frontend',
  },

  // ── Generic stacks ────────────────────────────────────────
  {
    id: 'node',
    name: 'Node.js',
    runtime: 'node',
    extensions: ['.ts', '.js', '.mjs', '.cjs'],
    entryPatterns: ['package.json', 'index.ts', 'index.js'],
    buildCommand: 'npm run build',
    startCommand: 'npm start',
    testCommand: 'npm test',
    dockerImage: 'node:20-alpine',
    category: 'backend',
  },
  {
    id: 'python',
    name: 'Python',
    runtime: 'python3',
    extensions: ['.py', '.pyi'],
    entryPatterns: ['requirements.txt', 'pyproject.toml', 'setup.py', 'Pipfile'],
    buildCommand: 'pip install -r requirements.txt',
    startCommand: 'python main.py',
    testCommand: 'pytest',
    dockerImage: 'python:3.12-slim',
    category: 'backend',
  },
  {
    id: 'go',
    name: 'Go',
    runtime: 'go',
    extensions: ['.go'],
    entryPatterns: ['go.mod', 'main.go'],
    buildCommand: 'go build ./...',
    startCommand: 'go run .',
    testCommand: 'go test ./...',
    dockerImage: 'golang:1.22-alpine',
    category: 'backend',
  },
  {
    id: 'ruby',
    name: 'Ruby',
    runtime: 'ruby',
    extensions: ['.rb', '.erb'],
    entryPatterns: ['Gemfile', 'Rakefile', 'config.ru'],
    buildCommand: 'bundle install',
    startCommand: 'bundle exec ruby app.rb',
    testCommand: 'bundle exec rspec',
    dockerImage: 'ruby:3.3-slim',
    category: 'backend',
  },
  {
    id: 'rust',
    name: 'Rust',
    runtime: 'cargo',
    extensions: ['.rs'],
    entryPatterns: ['Cargo.toml', 'Cargo.lock'],
    buildCommand: 'cargo build --release',
    startCommand: 'cargo run',
    testCommand: 'cargo test',
    dockerImage: 'rust:1.77-slim',
    category: 'backend',
  },
  {
    id: 'java',
    name: 'Java',
    runtime: 'java',
    extensions: ['.java', '.kt', '.kts'],
    entryPatterns: ['pom.xml', 'build.gradle', 'build.gradle.kts'],
    buildCommand: 'mvn package',
    startCommand: 'java -jar target/*.jar',
    testCommand: 'mvn test',
    dockerImage: 'eclipse-temurin:21-jre-alpine',
    category: 'backend',
  },
  {
    id: 'dotnet',
    name: '.NET',
    runtime: 'dotnet',
    extensions: ['.cs', '.fs', '.vb', '.csproj', '.fsproj'],
    entryPatterns: ['*.csproj', '*.fsproj', '*.sln', 'Program.cs'],
    buildCommand: 'dotnet build',
    startCommand: 'dotnet run',
    testCommand: 'dotnet test',
    dockerImage: 'mcr.microsoft.com/dotnet/aspnet:8.0',
    category: 'backend',
  },
  {
    id: 'static-site',
    name: 'Static Site',
    runtime: 'none',
    extensions: ['.html', '.css', '.svg'],
    entryPatterns: ['index.html'],
    dockerImage: 'nginx:alpine',
    category: 'static',
  },
] as const;
